# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWJlMzRiY2E0ZmM2ZjY3M2FmMmU3MmM0NzUwMWFjNmRjM2Q0ZmI1MDg5Zjc0ODQ3YTVkNzI0Y2Q4NjBmZDNiZjcyNGI3OTk5NjY4MjYxNzY2NWFmMTIzNGU3NWY0NzhkYjVjNzJkM2M3OTIxOTFiZmE1MTNhM2ViZmFlMDBmMjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
